const services=[
["api-gateway","Healthy","prod-us-east-1","12/12","142ms","0.12%","99.99%"],["auth-service","Healthy","prod-us-east-1","6/6","64ms","0.05%","99.99%"],["kafka-broker","Healthy","prod-us-east-1","5/5","18ms","0.02%","99.98%"],["media-storage-gw","Down","prod-ap-south-1","0/3","0ms","14.0%","98.90%"],["notification-worker","Healthy","prod-us-east-1","8/8","91ms","0.08%","99.96%"],["orders-service","Healthy","prod-us-east-1","10/10","188ms","0.15%","99.97%"],["otel-collector","Healthy","prod-us-east-1","4/4","12ms","0.01%","99.99%"],["payments-api","Degraded","prod-us-east-1","7/8","642ms","2.40%","99.82%"],["postgres-primary","Healthy","prod-us-east-1","3/3","22ms","0.01%","99.99%"],["prometheus","Healthy","prod-us-east-1","2/2","16ms","0.01%","99.99%"],["redis-cache","Healthy","prod-us-east-1","6/6","9ms","0.03%","99.99%"],["search-indexer","Degraded","prod-eu-west-1","5/6","820ms","1.70%","99.71%"]];
let deployments=[
["api-gateway","v3.18.2","Production","Success","a81f2d9","GitHub Actions"],["payments-api","v2.9.1","Production","In Progress","b4e193a","Argo CD sync"],["orders-service","v4.2.0","Production","Success","c09ab71","GitHub Actions"],["search-indexer","v1.16.3","Production","Failed","de2719b","Helm release"],["auth-service","v2.12.5","Staging","Success","ef91ac4","GitHub Actions"],["notification-worker","v1.8.4","Production","Rolled Back","fe6c812","Argo CD sync"]];
let incidents=[
{sev:"SEV1",status:"Investigating",title:"media-storage-gw pods unavailable in ap-south-1",detail:"PodCrashLooping and 5xx alerts fired. Traffic shifted to eu-west-1 via weighted DNS failover."},
{sev:"SEV2",status:"Monitoring",title:"Elevated p99 latency on payments-api",detail:"Latency increased after a dependency timeout. Capacity scaled and error rate is recovering."},
{sev:"SEV3",status:"Identified",title:"search-indexer consumer lag",detail:"Kafka consumer lag traced to a slow shard. Rebalancing is in progress."}];
const subtitles={overview:"Platform health across clusters and services",services:"Service health, latency, errors and availability",deployments:"Release history and deployment safety",incidents:"Incident response and operational recovery",observability:"Prometheus metrics, OpenTelemetry traces and Kubernetes signals"};
function badge(s){let c=/Healthy|Success|Resolved|Inactive/.test(s)?"good":/Degraded|Monitoring|Pending|In Progress|Identified/.test(s)?"warn":"bad";return '<span class="badge '+c+'">'+s+'</span>'}
function metric(label,value,sub){return '<div class="card"><div class="metric-label">'+label+'</div><div class="metric-value">'+value+'</div><div class="metric-sub">'+sub+'</div></div>'}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function chart(title,path1,path2){return '<div class="card"><h3>'+title+'</h3><div class="chart"><div class="spark"><svg viewBox="0 0 500 130" preserveAspectRatio="none"><polyline fill="none" stroke="#60a5fa" stroke-width="2" points="'+path1+'"/>'+(path2?'<polyline fill="none" stroke="#fbbf24" stroke-width="2" stroke-dasharray="5 4" points="'+path2+'"/>':'')+'</svg></div></div></div>'}
function overview(){
return '<div class="grid grid-4">'+metric("Healthy services","9","of 12 total services")+metric("Degraded","2","require attention")+metric("Active incidents","3","1 critical SEV1")+metric("Deploy success","79%","last 14 releases")+'</div><div class="section-title"><h2>Kubernetes clusters</h2><span class="badge">3 regions</span></div><div class="grid grid-3">'+
'<div class="card"><h3>prod-us-east-1 '+badge("Healthy")+'</h3><div class="mono">AWS EKS · us-east-1</div><div class="bar"><span style="width:72%"></span></div><p class="metric-sub">42 nodes · 318 pods · 72% CPU</p></div>'+
'<div class="card"><h3>prod-eu-west-1 '+badge("Healthy")+'</h3><div class="mono">AWS EKS · eu-west-1</div><div class="bar"><span style="width:61%"></span></div><p class="metric-sub">31 nodes · 226 pods · 61% CPU</p></div>'+
'<div class="card"><h3>prod-ap-south-1 '+badge("Degraded")+'</h3><div class="mono">GCP GKE · asia-south1</div><div class="bar"><span style="width:88%"></span></div><p class="metric-sub">18 nodes · 121 pods · 88% memory</p></div></div>'+
'<div class="grid grid-2" style="margin-top:16px"><div><div class="section-title"><h2>Recent deployments</h2></div>'+table(["Service","Version","Status"],deployments.slice(0,4).map(d=>[d[0],'<span class="mono">'+d[1]+'</span>',badge(d[3])]))+'</div><div><div class="section-title"><h2>Active incidents</h2></div>'+incidents.map(i=>'<div class="card incident '+(i.sev==="SEV2"?"sev2":"")+'" style="margin-bottom:9px"><span class="badge bad">'+i.sev+'</span> '+badge(i.status)+'<h3 style="margin-top:10px">'+i.title+'</h3></div>').join('')+'</div></div>'}
function servicesPage(){let rows=services.map(s=>['<strong>'+s[0]+'</strong>',badge(s[1]),'<span class="mono">'+s[2]+'</span>',s[3],s[4],s[5],s[6]]);return '<div class="grid grid-3">'+metric("Healthy","9","services operating normally")+metric("Degraded","2","performance impacted")+metric("Down","1","service unavailable")+'</div><div class="section-title"><h2>Services</h2></div><div class="controls"><input id="service-search" class="input" placeholder="Search services..."><select id="status-filter" class="select"><option>All</option><option>Healthy</option><option>Degraded</option><option>Down</option></select></div><div id="service-table">'+table(["Service","Status","Cluster","Replicas","p99","Errors","Uptime"],rows)+'</div>'}
function deploymentsPage(){return '<div class="grid grid-4">'+metric("Total releases","14","tracked releases")+metric("Success rate","79%","last 14 releases")+metric("Failed","1","requires investigation")+metric("Rollbacks","1","automatic recovery")+'</div><div class="section-title"><h2>Deployment history</h2><button class="btn primary" id="trigger-deploy">Trigger deployment</button></div>'+table(["Service","Version","Environment","Status","Commit","Pipeline","Action"],deployments.map((d,i)=>[d[0],'<span class="mono">'+d[1]+'</span>',d[2],badge(d[3]),'<span class="mono">'+d[4]+'</span>',d[5],d[3]==="Success"?'<button class="btn danger-btn rollback" data-i="'+i+'">Rollback</button>':"—"]))}
function incidentsPage(){return '<div class="grid grid-3">'+metric("Active","3","open incidents")+metric("Active SEV1","1","critical impact")+metric("Resolved","2","last 7 days")+'</div><div class="section-title"><h2>Incident queue</h2><button class="btn primary" id="declare">Declare incident</button></div><div class="grid grid-2"><div>'+incidents.map((i,n)=>'<div class="card incident '+(i.sev==="SEV2"?"sev2":"")+'" style="margin-bottom:10px"><span class="badge bad">'+i.sev+'</span> '+badge(i.status)+'<h3 style="margin-top:10px">'+i.title+'</h3><p class="metric-sub">'+i.detail+'</p><button class="btn advance" data-i="'+n+'">Advance status</button></div>').join('')+'</div><div class="card"><h3>SEV1 timeline</h3><div class="timeline"><p><b>10:14</b> PodCrashLooping and 5xx alerts fired.</p><p><b>10:18</b> Traffic shifted to eu-west-1 via weighted DNS failover.</p><p><b>10:27</b> Pods OOMKilled after autoscaler rebalanced onto smaller instances.</p><p><b>10:41</b> Memory limits adjusted; replacement pods stabilizing.</p></div></div></div>'}
function observabilityPage(tab="golden"){let tabs='<div class="tabs"><button class="tab '+(tab==="golden"?"active":"")+'" data-tab="golden">Golden signals</button><button class="tab '+(tab==="resources"?"active":"")+'" data-tab="resources">Resources</button><button class="tab '+(tab==="k8s"?"active":"")+'" data-tab="k8s">Kubernetes</button></div>';let body;if(tab==="resources")body='<div class="grid grid-2">'+chart("CPU usage","0,90 60,82 120,95 180,58 240,70 300,45 360,60 420,40 500,52")+chart("Memory working set","0,82 60,80 120,74 180,68 240,63 300,58 360,50 420,47 500,44")+chart("Network I/O","0,105 60,70 120,88 180,48 240,76 300,35 360,69 420,42 500,61")+chart("Disk IOPS","0,95 60,92 120,61 180,84 240,49 300,78 360,55 420,72 500,64")+'</div>';else if(tab==="k8s")body='<div class="grid grid-2">'+chart("Ready pods · kube_deployment_status_replicas_available","0,70 80,70 160,70 220,88 280,70 360,70 430,70 500,70","0,70 80,70 160,70 220,70 280,70 360,70 430,70 500,70")+chart("HPA scaling events · desired replicas","0,100 80,100 160,72 240,72 320,42 400,42 500,65")+chart("Container restarts","0,110 80,110 160,110 220,45 280,110 360,110 430,80 500,110")+chart("Node pressure","0,48 80,52 160,47 240,55 320,50 400,57 500,51")+'</div>';else body='<div class="controls"><select class="select" id="promql"><option>p99 request latency</option><option>Request rate</option><option>5xx error ratio</option><option>Container CPU</option><option>Pod restarts</option></select><span class="mono" id="query">histogram_quantile(0.99, sum(rate(http_server_duration_bucket[5m])) by (le))</span></div><div class="grid grid-2">'+chart("p99 request latency","0,105 50,95 100,102 150,82 200,90 250,54 300,72 350,38 400,68 450,44 500,58")+chart("Request rate","0,88 50,74 100,80 150,60 200,65 250,48 300,57 350,42 400,50 450,39 500,45")+'</div><div class="grid grid-2" style="margin-top:16px"><div class="card"><h3>Distributed traces · OpenTelemetry</h3>'+[["POST /api/v1/checkout","482ms",96],["authorize · auth-service","38ms",18],["create_order · orders-service","310ms",64],["INSERT orders · postgres-primary","74ms",30],["charge_card · payments-api","196ms",48],["SET session · redis-cache","9ms",9],["publish order.created · kafka-broker","24ms",15]].map(x=>'<div class="trace-row"><span>'+x[0]+'</span><span class="trace-span" style="width:'+x[2]+'%"></span><span>'+x[1]+'</span></div>').join('')+'</div><div class="card"><h3>Alertmanager rules</h3>'+[["HighP99Latency","Firing","SEV2"],["ErrorBudgetBurn","Pending","SEV1"],["PodCrashLooping","Firing","SEV2"],["NodeMemoryPressure","Inactive","SEV3"],["KafkaConsumerLag","Inactive","SEV3"],["CertificateExpiry","Inactive","SEV4"]].map(x=>'<p><span class="mono">'+x[0]+'</span> '+badge(x[1])+' <span class="badge">'+x[2]+'</span> <button class="btn silence">Silence</button></p>').join('')+'</div></div>';return tabs+body}
function render(page,tab){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.getElementById("page-title").textContent=page[0].toUpperCase()+page.slice(1);document.getElementById("page-subtitle").textContent=subtitles[page];let c=document.getElementById("content");c.innerHTML=page==="overview"?overview():page==="services"?servicesPage():page==="deployments"?deploymentsPage():page==="incidents"?incidentsPage():observabilityPage(tab);bind(page)}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function bind(page){if(page==="services"){let q=document.getElementById("service-search"),f=document.getElementById("status-filter");let go=()=>{let a=services.filter(s=>s[0].includes(q.value.toLowerCase())&&(f.value==="All"||s[1]===f.value));document.getElementById("service-table").innerHTML=table(["Service","Status","Cluster","Replicas","p99","Errors","Uptime"],a.map(s=>['<strong>'+s[0]+'</strong>',badge(s[1]),'<span class="mono">'+s[2]+'</span>',s[3],s[4],s[5],s[6]]))};q.oninput=go;f.onchange=go}if(page==="deployments"){document.getElementById("trigger-deploy").onclick=()=>{deployments.unshift(["api-gateway","v3.19.0","Production","In Progress","f91c7aa","GitHub Actions"]);toast("Deployment triggered (demo)");render("deployments")};document.querySelectorAll(".rollback").forEach(b=>b.onclick=()=>{deployments[b.dataset.i][3]="Rolled Back";toast("Rollback completed (demo)");render("deployments")})}if(page==="incidents"){document.getElementById("declare").onclick=()=>{incidents.unshift({sev:"SEV3",status:"Investigating",title:"New demo incident",detail:"Incident created from the portfolio console."});toast("Incident declared (demo)");render("incidents")};document.querySelectorAll(".advance").forEach(b=>b.onclick=()=>{let seq=["Investigating","Identified","Monitoring","Resolved"],i=incidents[b.dataset.i],n=Math.min(seq.indexOf(i.status)+1,3);i.status=seq[n];toast("Incident moved to "+i.status);render("incidents")})}if(page==="observability"){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>render("observability",b.dataset.tab));document.querySelectorAll(".silence").forEach(b=>b.onclick=()=>{b.textContent="Silenced";toast("Alert silenced (demo)")});let p=document.getElementById("promql");if(p)p.onchange=()=>{let m={"p99 request latency":"histogram_quantile(0.99, sum(rate(http_server_duration_bucket[5m])) by (le))","Request rate":"sum(rate(http_requests_total[1m]))","5xx error ratio":"sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))","Container CPU":"sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)","Pod restarts":"increase(kube_pod_container_status_restarts_total[5m])"};document.getElementById("query").textContent=m[p.value]}}}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>render(b.dataset.page));setInterval(()=>document.getElementById("clock").textContent=new Date().toLocaleTimeString(),1000);render("overview");